it will throw an exception and the program would fail.
